/* PC inference test  -  auto-generated by cmsis_nn_codegen.py */
#include <stdio.h>
#include <stdint.h>
#include <math.h>

#include "generated/my_model_run.h"

int main(void)
{
    int8_t input[MY_MODEL_INPUT_SIZE];
    int8_t output[MY_MODEL_OUTPUT_SIZE];

    printf("=====================================\n");
    printf(" CMSIS-NN v7 PC Inference Test\n");
    printf("=====================================\n\n");

    int mismatches = 0;

    for (int q = -128; q < 128; q++)
    {
        input[0] = (int8_t)q;

        my_model_run(input, output);

        float x   = (q          - MY_MODEL_INPUT_ZP)  * MY_MODEL_INPUT_SCALE;
        float y   = (output[0]  - MY_MODEL_OUTPUT_ZP) * MY_MODEL_OUTPUT_SCALE;
        float ref = sinf(x);
        float err = fabsf(y - ref);

        if (err > 0.02f)
            mismatches++;

        printf("q=%4d  x=%8.4f  y=%8.4f  sin(x)=%8.4f  err=%8.5f\n",
               q, x, y, ref, err);
    }

    printf("\n-------------------------------------\n");
    printf("Total large mismatches (>0.02): %d\n", mismatches);
    printf("-------------------------------------\n");

    return 0;
}
